# Generated by Django 4.2.25 on 2026-01-03 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsletter', '0015_migrate_accountids_to_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
            },
        ),
        migrations.CreateModel(
            name='OrganisationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='newsletter.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='members',
            field=models.ManyToManyField(related_name='organisations', through='newsletter.OrganisationMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='organisationmember',
            index=models.Index(fields=['user', 'role'], name='newsletter__user_id_e857a8_idx'),
        ),
        migrations.AddIndex(
            model_name='organisationmember',
            index=models.Index(fields=['organisation', 'role'], name='newsletter__organis_87aed2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organisationmember',
            unique_together={('organisation', 'user')},
        ),
        migrations.AddIndex(
            model_name='organisation',
            index=models.Index(fields=['slug'], name='newsletter__slug_7d665c_idx'),
        ),
        migrations.AddIndex(
            model_name='organisation',
            index=models.Index(fields=['is_active'], name='newsletter__is_acti_f663d0_idx'),
        ),
    ]
