# Generated by Django 4.2.25 on 2026-01-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0016_organisation_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='organisationId',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='organisationId',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='organisationIds',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='organisationId',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='urldata',
            name='organisationId',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
